version: 2.1
orbs:
  gem: zfhui/ruby-gem@0.2.1
jobs:
  test-with-ruby-latest:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: latest
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 2.2.19
  test-with-ruby-2-3-8:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.3.8
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 1.17.3
  build-and-release:
    working_directory: ~/repo
    executor: gem/default
    steps:
      - gem/build:
          gem-name: blinkist-airbrake-scrubber
      - gem/release:
          gem-name: blinkist-airbrake-scrubber
          gem-credentials-env-name: $RUBYGEMS_API_KEY
  license-check:
    resource_class: small
    working_directory: ~/app
    docker:
      - image: cimg/ruby:2.7.2

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache-

      - run:
          name: Bundle Install
          command: |
            gem install bundler:2.2.26
            bundle config set path "vendor/bundle" && bundle config set clean "true"
            bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Clone github tooling
          command: git clone --depth=1 git@github.com:blinkist/github-tooling.git

      - run:
          name: "Copy License configuration file"
          command: |
            mkdir docs
            cp github-tooling/data/general-license-allowlist.yml docs/dependency_decisions.yml
      - run:
          name: run license_finder
          # Fails the build if new unapproved licenses are found
          command: bundle exec license_finder --decisions_file docs/dependency_decisions.yml
workflows:
  test:
    jobs:
      - test-with-ruby-latest
      - test-with-ruby-2-3-8
      - build-and-release:
          requires:
            - test-with-ruby-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
