version: 2.1
orbs:
  gem: zfhui/ruby-gem@0.2.1
jobs:
  test-with-ruby-latest:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: latest
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 2.2.19
  test-with-ruby-2-3-8:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.3.8
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 1.17.3
  build-and-release:
    working_directory: ~/repo
    executor: gem/default
    steps:
      - gem/build:
          gem-name: blinkist-airbrake-scrubber
      - gem/release:
          gem-name: blinkist-airbrake-scrubber
          gem-credentials-env-name: $RUBYGEMS_API_KEY

workflows:
  test:
    jobs:
      - test-with-ruby-latest
      - test-with-ruby-2-3-6
      - build-and-release:
          requires:
            - test-with-ruby-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
