version: 2.1
orbs:
  gem: zfhui/ruby-gem@0.2.1
jobs:
  test-with-ruby-latest:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: latest
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 2.3.5
  test-with-ruby-2-7:
    working_directory: ~/repo
    executor:
      name: gem/default
      tag: 2.7.5
    steps:
      - gem/setup-and-test:
          gemspec: blinkist-airbrake-scrubber.gemspec
          bundler-version: 2.3.5
  build-and-release:
    working_directory: ~/repo
    executor: gem/default
    steps:
      - gem/build:
          gem-name: blinkist-airbrake-scrubber
      - gem/release:
          gem-name: blinkist-airbrake-scrubber
          gem-credentials-env-name: $RUBYGEMS_API_KEY

workflows:
  test:
    jobs:
      - test-with-ruby-latest
      - test-with-ruby-2-7
      - build-and-release:
          requires:
            - test-with-ruby-latest
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              only:
                - main
